### PR TITLE
Fix #214

### LINKED ISSUE #214: Unable to propose a proposal with an `approve_proposal` operation
_From @abitmore on June 4, 2016 19:0_

Got this message while trying to propose a proposal with an `approve_proposal` operation:

```
10 assert_exception: Assert Exception
other.size() == 0:
    {}
    th_a  proposal_evaluator.cpp:54 do_evaluate
```

The issue is probably caused by lack of size checking on `auth.key_auths` before [this line in proposal.cpp](https://github.com/cryptonomex/graphene/blob/2.0.160328/libraries/chain/protocol/proposal.cpp#L92), imo the code could be

```
if( auth.key_auths.size() > 0 )
   o.emplace_back( std::move(auth) );
```

To fix this issue, a hard fork is needed.

_Copied from original issue: cryptonomex/graphene#658_

### PR DESCRIPTION
**Pull request by pmconrad**
Unit test + fix for issue #214, as suggested by <strike>@vikramrajkumar</strike> @abitmore

### CODE REVIEW

File: libraries/chain/hardfork.d/CORE_214.hf [hunk 1]
```diff
@@ -0,0 +1,4 @@
+// bitshares-core #214 Process to reset a Smartcoin after a Black Swan
```
Comment (abitmore) [inline libraries/chain/hardfork.d/CORE_214.hf]: Please update this description.

**Comment by pmconrad** [comment]
Oops, sorry. :-)

**Comment by xeroc** [comment]
Hossa, it took me a while to see that there is a `pup` and a `pop` in the proposal ;)
