### PR TITLE
Fix #944 unexpected "Missing Active Authority" message for update_asset_issuer

### LINKED ISSUE #944: inconsistent error message for update_asset_issuer
Issues:
For the new feature [BSIP29](https://github.com/bitshares/bsips/blob/master/bsip-0029.md), if only import activity key of the asset issuer without import the owner key, then call the API update_asset_issuer. It will fail with this message  **Missing Active Authority 1.2.22628**
In fact, the activity key is provided, user may get confused here.

Expect:
It should warning Missing Owner Authority.

### PR DESCRIPTION
**Pull request by abitmore**
PR for #944.

This should not break anything. To be safe, sync the chain with `--force-validate` option.

```
./witness_node --force-validate
```

### CODE REVIEW

File: tests/tests/authority_tests.cpp [hunk 1]
```diff
@@ -1448,6 +1448,69 @@ BOOST_FIXTURE_TEST_CASE( parent_owner_test, database_fixture )
...
+      signed_transaction tx;
+      account_update_operation op;
+      op.account = alice_id;
+      op.owner = authority( 1, alice_active_pub, 1 );
+      tx.operations.push_back( op );
+
+      // https://github.com/bitshares/bitshares-core/issues/944
+      GRAPHENE_REQUIRE_THROW( tx.verify_authority( db.get_chain_id(), get_active, get_owner ),
+                              graphene::chain::tx_missing_owner_auth );
+
```
Comment (pmconrad) [inline tests/tests/authority_tests.cpp]: Please add signature from alice_active and verify that it still complains about missing owner, then replace with signature from alice_owner a verify that is doesn't throw anymore.
