### PR TITLE
#463, Add API to query for open orders of one account in one market

### LINKED ISSUE #811: how to use database API in cli_wallet for example  get_full_accounts  method?
unlocked >>> get_full_accounts
get_full_accounts
10 assert_exception: Assert Exception
itr != _by_name.end(): no method with name 'get_full_accounts'

### PR DESCRIPTION
**Pull request by cifer-lee**
Local tests ok:

1. call this api through websocket
2. call this api through cli_wallet

But I'm not very sure if this pr meets the requests of #463, pls help pointing out if not. 

Update:

may fix #811 btw

### CODE REVIEW

**Comment by abitmore** [comment]
Wanted parameters: account, market (base and quote) and fields for pagination.

**Comment by cifer-lee** [comment]
the `get_account_orders()` api I added mostly copied from `get_full_account()`, the first parameter is a array of accounts.

Per the requests and for simplicity, I think new api's first parameter can just be one account name (or id), is there any case that will request multiple accounts' orders at one time?

**Comment by abitmore** [comment]
@cifer-lee IMHO the new APIs should only use single account, but not an array. Thanks.

File: libraries/app/database_api.cpp [hunk 1]
```diff
@@ -624,6 +625,54 @@ vector<optional<account_object>> database_api_impl::get_accounts(const vector<ac
...
+   }
+   if (account == nullptr)
+       return results;
+
+   auto assets = lookup_asset_symbols( {base, quote} );
+   auto base_id = assets[0]->id;
+   auto quote_id = assets[1]->id;
+
+   // Add the account's orders
+   auto order_range = _db.get_index_type<limit_order_index>().indices().get<by_account>().equal_range(account->id);
```
Comment (abitmore) [inline libraries/app/database_api.cpp]: Perhaps best to add an index for this API? Iterating with `continue` below is inefficient.

File: libraries/app/database_api.cpp [hunk 2]
```diff
@@ -624,6 +625,54 @@ vector<optional<account_object>> database_api_impl::get_accounts(const vector<ac
    return result;
 }
 
+vector<limit_order_object> database_api::get_account_limit_orders( const string& name_or_id, const string& base, const string& quote, fc::time_point_sec expire, uint32_t limit)
+{
+   return my->get_account_limit_orders( name_or_id, base, quote, expire, limit );
+}
+
+vector<limit_order_object> database_api_impl::get_account_limit_orders( const string& name_or_id, const string& base, const string& quote, fc::time_point_sec expire, uint32_t limit)
+{
```
Comment (abitmore) [inline libraries/app/database_api.cpp]: Please check if `limit` is too big. Since `limit_order` is relatively small, I think we can return a bit more per page.

**Comment by cifer-lee** [comment]
@abitmore Thanks for your comments, I had think before made these changes.

IMHO by expiration maybe simple to use, since client would not know order id? But client could easily fetch account's orders by specifying an timestamp and a limit.

Shortcomings are that expiration is not ordered in limit_order_index, and many orders not specifying expiration may default to year 2038. Actually, I wish limit order could have a create time, so we can querying account's orders this way: query 100 of Sam's limit orders before 2018-04-18, time descending.

**Comment by abitmore** [comment]
Clients software do know order id, although perhaps aren't showing it on UI.

My thoughts about pagination:
* with a given id, get price of the order;
* query with `by_price` index, with lower bound from tuple `(price,id)` as lower bound, then iterate forward.

**Comment by cifer-lee** [comment]
> query with `by_price` index, with lower bound from tuple `(price,id)` as lower bound, then iterate forward.

But this means filter the target account iteratively, not this back to the inefficiency issue you pointed above?

**Comment by abitmore** [comment]
@cifer-lee sorry, I've noticed the issue then updated the comment later. Please check again.

**Comment by abitmore** [comment]
@cifer-lee my thoughts about pagination (two steps for one API query):
* with a given id, get price of the order;
* query with an appropriate index, with lower bound from tuple `(account,price,id)` as lower bound, then iterate forward.

**Comment by abitmore** [comment]
@cifer-lee some changes in the last commit are not ideal:
* we need "base" and "quote" in parameter list, otherwise there is no good way to query for the first page;
* we need `(account,price,id)` index to query for the 2nd page, but not `(account,id,price)`.

**Comment by cifer-lee** [comment]
@abitmore Have fixed per to discussion on telegram, please check~

File: libraries/app/database_api.cpp [hunk 3]
```diff
@@ -624,6 +625,89 @@ vector<optional<account_object>> database_api_impl::get_accounts(const vector<ac
...
+       upper_itr = index_by_account.upper_bound(std::make_tuple(account->id, price::min(base_id, quote_id)));
+   } else if (ostart_id) {
+       // in case of the order been deleted during page querying
+       if (!_db.find_object(*ostart_id)) {
+           if (ostart_price) {
+               lower_itr = index_by_account.lower_bound(std::make_tuple(account->id, (*ostart_price).max(), *ostart_id));
+               upper_itr = index_by_account.upper_bound(std::make_tuple(account->id, (*ostart_price).min(), *ostart_id));
+           } else {
+               // start order id been deleted, yet not provided price either, return empty
+               return results;
```
Comment (abitmore) [inline libraries/app/database_api.cpp]: I'd rather throw out an exception here.

File: libraries/app/database_api.cpp [hunk 4]
```diff
@@ -624,6 +625,89 @@ vector<optional<account_object>> database_api_impl::get_accounts(const vector<ac
...
+   limit_order_multi_index_type::index<by_account>::type::const_iterator upper_itr;
+
+   // if both order_id and price are invalid, query the first page
+   if (!ostart_id && !ostart_price) {
+       lower_itr = index_by_account.lower_bound(std::make_tuple(account->id, price::max(base_id, quote_id)));
+       upper_itr = index_by_account.upper_bound(std::make_tuple(account->id, price::min(base_id, quote_id)));
+   } else if (ostart_id) {
+       // in case of the order been deleted during page querying
+       if (!_db.find_object(*ostart_id)) {
+           if (ostart_price) {
```
Comment (abitmore) [inline libraries/app/database_api.cpp]: Please avoid using `optional::bool()`.

File: libraries/app/database_api.cpp [hunk 5]
```diff
@@ -624,6 +625,89 @@ vector<optional<account_object>> database_api_impl::get_accounts(const vector<ac
...
+   }
+   if (account == nullptr)
+       return results;
+
+   auto assets = lookup_asset_symbols( {base, quote} );
+   FC_ASSERT( assets[0], "Invalid base asset symbol: ${s}", ("s",base) );
+   FC_ASSERT( assets[1], "Invalid quote asset symbol: ${s}", ("s",quote) );
+
+   auto base_id = assets[0]->id;
+   auto quote_id = assets[1]->id;
```
Comment (abitmore) [inline libraries/app/database_api.cpp]: Here is the best place to check whether the start price is consistent with `base` and `quote` parameters. If not, IMHO best to throw out an exception.

File: libraries/app/database_api.cpp [hunk 6]
```diff
@@ -624,6 +625,89 @@ vector<optional<account_object>> database_api_impl::get_accounts(const vector<ac
...
+               return results;
+           }
+       } else {
+           const limit_order_object &loo = _db.get(*ostart_id);
+
+           lower_itr = index_by_account.lower_bound(std::make_tuple(account->id, loo.sell_price.max(), *ostart_id));
+           upper_itr = index_by_account.upper_bound(std::make_tuple(account->id, loo.sell_price.min(), *ostart_id));
+       }
+  } else { // if reach here start_price must be valid
+      lower_itr = index_by_account.lower_bound(std::make_tuple(account->id, (*ostart_price).max()));
```
Comment (abitmore) [inline libraries/app/database_api.cpp]: Using `max` here is wrong.

File: libraries/app/include/graphene/app/database_api.hpp [hunk 7]
```diff
@@ -268,6 +268,25 @@ class database_api
        */
       vector<optional<account_object>> get_accounts(const vector<account_id_type>& account_ids)const;
 
+      /**
+       * @brief Fetch all orders relevant to the specified accounts sorted descendingly by price
```
Comment (abitmore) [inline libraries/app/include/graphene/app/database_api.hpp]: Change `accounts` to `account`.

File: libraries/app/include/graphene/app/database_api.hpp [hunk 8]
```diff
@@ -268,6 +268,25 @@ class database_api
...
+       *
+       * @param name_or_id  Each item must be the name or ID of an account to retrieve
```
Comment (abitmore) [inline libraries/app/include/graphene/app/database_api.hpp]: Remove `Each item must be `.

File: libraries/app/include/graphene/app/database_api.hpp [hunk 9]
```diff
@@ -268,6 +268,25 @@ class database_api
...
+       * @param base  Base asset
+       * @param quote  Quote asset
+       * @param limit  Max items to fetch
+       * @param start_id  Start order id, fetch orders which price lower than this order
+       * @param start_price  Fetch orders with price lower than this price
```
Comment (abitmore) [inline libraries/app/include/graphene/app/database_api.hpp]: `lower` is not accurate.

File: libraries/app/include/graphene/app/database_api.hpp [hunk 10]
```diff
@@ -268,6 +268,25 @@ class database_api
...
       vector<optional<account_object>> get_accounts(const vector<account_id_type>& account_ids)const;
 
+      /**
+       * @brief Fetch all orders relevant to the specified accounts sorted descendingly by price
+       *
+       * @param name_or_id  Each item must be the name or ID of an account to retrieve
+       * @param base  Base asset
+       * @param quote  Quote asset
+       * @param limit  Max items to fetch
+       * @param start_id  Start order id, fetch orders which price lower than this order
```
Comment (abitmore) [inline libraries/app/include/graphene/app/database_api.hpp]: `lower` is not accurate. BTW if the price is the same, order id should be equal or higher?

File: libraries/app/include/graphene/app/database_api.hpp [hunk 11]
```diff
@@ -268,6 +268,25 @@ class database_api
...
+       * @param start_price  Fetch orders with price lower than this price
+       *
+       * @return List of orders from @ref name_or_id to the corresponding account
+       *
+       * @note
+       * 1. if @ref name_or_id cannot be tied to an account, empty results will be returned
```
Comment (abitmore) [inline libraries/app/include/graphene/app/database_api.hpp]: Change `results` to `result`.

File: libraries/app/include/graphene/app/database_api.hpp [hunk 12]
```diff
@@ -268,6 +268,25 @@ class database_api
        */
       vector<optional<account_object>> get_accounts(const vector<account_id_type>& account_ids)const;
 
+      /**
+       * @brief Fetch all orders relevant to the specified accounts sorted descendingly by price
+       *
+       * @param name_or_id  Each item must be the name or ID of an account to retrieve
+       * @param base  Base asset
+       * @param quote  Quote asset
+       * @param limit  Max items to fetch
```
Comment (abitmore) [inline libraries/app/include/graphene/app/database_api.hpp]: Please mention the limitation of this parameter.

File: libraries/wallet/include/graphene/wallet/wallet.hpp [hunk 13]
```diff
@@ -378,6 +378,7 @@ class wallet_api
      vector<operation_detail>  get_relative_account_history(string name, uint32_t stop, int limit, uint32_t start)const;
 
       vector<bucket_object>             get_market_history(string symbol, string symbol2, uint32_t bucket, fc::time_point_sec start, fc::time_point_sec end)const;
+      vector<limit_order_object>        get_account_limit_orders( const string& name_or_id, const string &base, const string &quote, uint32_t limit = 100, optional<limit_order_id_type> ostart_id = optional<limit_order_id_type>(), optional<price> ostart_price = optional<price>());
```
Comment (abitmore) [inline libraries/wallet/include/graphene/wallet/wallet.hpp]: Please add docs.

File: libraries/app/database_api.cpp [hunk 14]
```diff
@@ -624,6 +625,89 @@ vector<optional<account_object>> database_api_impl::get_accounts(const vector<ac
...
 }
 
+vector<limit_order_object> database_api::get_account_limit_orders( const string& name_or_id, const string &base, const string &quote, uint32_t limit, optional<limit_order_id_type> ostart_id, optional<price> ostart_price)
+{
+   return my->get_account_limit_orders( name_or_id, base, quote, limit, ostart_id, ostart_price );
+}
+
+vector<limit_order_object> database_api_impl::get_account_limit_orders( const string& name_or_id, const string &base, const string &quote, uint32_t limit, optional<limit_order_id_type> ostart_id, optional<price> ostart_price)
+{
+   FC_ASSERT( limit <= 100 );
```
[the remark this answers is not in the document]
Comment (cifer-lee) [reply libraries/app/database_api.cpp]: ok, but why 101 easier for pagination?

File: libraries/app/database_api.cpp [hunk 15]
```diff
@@ -624,6 +625,89 @@ vector<optional<account_object>> database_api_impl::get_accounts(const vector<ac
...
+   // if both of them are valid, query by both
+   const auto& index_by_account = _db.get_index_type<limit_order_index>().indices().get<by_account>();
+   limit_order_multi_index_type::index<by_account>::type::const_iterator lower_itr;
+   limit_order_multi_index_type::index<by_account>::type::const_iterator upper_itr;
+
+   // if both order_id and price are invalid, query the first page
+   if (!ostart_id && !ostart_price) {
+       lower_itr = index_by_account.lower_bound(std::make_tuple(account->id, price::max(base_id, quote_id)));
+       upper_itr = index_by_account.upper_bound(std::make_tuple(account->id, price::min(base_id, quote_id)));
+   } else if (ostart_id) {
```
[the remark this answers is not in the document]
Comment (cifer-lee) [reply libraries/app/database_api.cpp]: got it, but why avoid using optional::bool()?

[the remark this answers is not in the document]
Comment (abitmore) [reply libraries/app/database_api.cpp]: https://github.com/bitshares/bitshares-fc/blob/master/include/fc/optional.hpp#L190-L192
```
      // this operation is not safe and can result in unintential 
      // casts and comparisons, use valid() or !! 
      explicit operator bool()const  { return _valid;  }
```
I can be wrong though. Since `operator bool()` is `explicit`, I didn't get what conversion will be done when calling `if(ostart_id)`.

File: libraries/app/database_api.cpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (abitmore) [reply libraries/app/database_api.cpp]: Usually we use 100, 50 or etc as page size. Since we use `lower_bound` here, if pass in the last item of last page, with `100` as limit we can get only 99 new items (although it's possible to get around it e.g. pass in `last_id+1` but it's not convenient).

File: libraries/app/database_api.cpp (hunk 3 above)
Comment (cifer-lee) [reply libraries/app/database_api.cpp]: ok I will change `find_object` to `get`, since `get` will throw exception when fail

File: libraries/app/database_api.cpp [hunk 16]
```diff
@@ -624,6 +625,90 @@ vector<optional<account_object>> database_api_impl::get_accounts(const vector<ac
...
+
+   // if both order_id and price are invalid, query the first page
+   if (!ostart_id.valid() && !ostart_price.valid()) {
+       lower_itr = index_by_account.lower_bound(std::make_tuple(account->id, price::max(base_id, quote_id)));
+       upper_itr = index_by_account.upper_bound(std::make_tuple(account->id, price::min(base_id, quote_id)));
+   } else if (ostart_id.valid()) {
+       // in case of the order been deleted during page querying
+       const limit_order_object *p_loo = nullptr;
+
+       if (!(p_loo = static_cast<const limit_order_object *>(_db.find_object(*ostart_id)))) {
```
[the remark this answers is not in the document]
Comment (cifer-lee) [reply libraries/app/database_api.cpp]: `_db.find()` will throw exception on fail, give me no change to use `ostart_price` getting lower bound

File: libraries/app/include/graphene/app/database_api.hpp [hunk 17]
```diff
@@ -268,6 +268,25 @@ class database_api
        */
       vector<optional<account_object>> get_accounts(const vector<account_id_type>& account_ids)const;
 
+      /**
+       * @brief Fetch all orders relevant to the specified account sorted descendingly by price
```
[the remark this answers is not in the document]
Comment (cifer-lee) [reply libraries/app/include/graphene/app/database_api.hpp]: depend on wether ui need it?
if need I can add this api

[the remark this answers is not in the document]
Comment (abitmore) [reply libraries/app/include/graphene/app/database_api.hpp]: There are use cases, but not popular: "I have many open orders, I don't remember what markets are they in, just want to get them all". I think it's low priority.

File: libraries/app/database_api.cpp (hunk 16 above)
[the remark this answers is not in the document]
Comment (abitmore) [reply libraries/app/database_api.cpp]: `find()` can return `nullptr`, so should be fine.

In regards to the use of `assert()`, actually I'm not sure if it's better to change them to `FC_ASSERT`. Main reason is `assert()` will be skipped when building in Release mode for better performance, but by doing so we may have skipped some important checking; another reason is the abortion behavior you've noticed. More info in https://github.com/bitshares/bitshares-core/issues/511.

File: libraries/app/database_api.cpp [hunk 18]
```diff
@@ -624,6 +625,87 @@ vector<optional<account_object>> database_api_impl::get_accounts(const vector<ac
...
+   auto quote_id = assets[1]->id;
+
+   if (ostart_price.valid()) {
+       FC_ASSERT(ostart_price->base.asset_id == base_id, "Base asset inconsistent with start price");
+       FC_ASSERT(ostart_price->quote.asset_id == quote_id, "Quote asset inconsistent with start price");
+   }
+
+   const auto& index_by_account = _db.get_index_type<limit_order_index>().indices().get<by_account>();
+   limit_order_multi_index_type::index<by_account>::type::const_iterator lower_itr;
+   limit_order_multi_index_type::index<by_account>::type::const_iterator upper_itr;
```
Comment (abitmore) [inline libraries/app/database_api.cpp]: Actually `upper_itr` can be initialized here, no need to be initialized in `if/else` block below, since the results will be the same.

File: tests/tests/database_api_tests.cpp [hunk 19]
```diff
@@ -692,4 +692,101 @@ BOOST_AUTO_TEST_CASE( lookup_vote_ids )
...
+   }
+
+   graphene::app::database_api db_api(db);
+   std::vector<limit_order_object> results;
+   limit_order_object o;
+
+   // query with no constraint, expected:
+   // 1. up to 101 orders returned
+   // 2. orders were sorted by price desendingly
+   results = db_api.get_account_limit_orders(seller.name, "BTS", "CNY");
```
Comment (abitmore) [inline tests/tests/database_api_tests.cpp]: Change "BTS" to the corresponding macro or use a local variable, otherwise this test case will fail in testnet branch.

File: tests/tests/database_api_tests.cpp [hunk 20]
```diff
@@ -692,4 +692,101 @@ BOOST_AUTO_TEST_CASE( lookup_vote_ids )
...
+   BOOST_CHECK(results.size() == 101);
+   for (int i = 0 ; i < results.size() - 1 ; ++i) {
+     BOOST_CHECK(results[i].sell_price >= results[i+1].sell_price);
+   }
```
Comment (abitmore) [inline tests/tests/database_api_tests.cpp]: Check if the first item and the last item are correct (also best to add this check to test cases below).

File: tests/tests/database_api_tests.cpp [hunk 21]
```diff
@@ -692,4 +692,101 @@ BOOST_AUTO_TEST_CASE( lookup_vote_ids )
...
+   results.clear();
+
+   // query with specified limit, expected:
+   // 1. up to specified amount of orders returned
+   // 2. orders were sorted by price desendingly
+   results = db_api.get_account_limit_orders(seller.name, "BTS", "CNY", 50);
+   results = db_api.get_account_limit_orders(seller.name, "BTS", "CNY", 50);
```
Comment (abitmore) [inline tests/tests/database_api_tests.cpp]: Redundant code?

File: tests/tests/database_api_tests.cpp [hunk 22]
```diff
@@ -692,4 +692,101 @@ BOOST_AUTO_TEST_CASE( lookup_vote_ids )
...
+   }
+
+   o = results.back();
+   results.clear();
+
+   cancel_limit_order(o); // NOTE 3: this time the canceled order was in scope
+                          // of the lowest price 150 orders
+   results = db_api.get_account_limit_orders(seller.name, "BTS", "CNY", 101,
+       limit_order_id_type(o.id), o.sell_price);
+   BOOST_CHECK(results.size() <= 101);
```
Comment (abitmore) [inline tests/tests/database_api_tests.cpp]: We know how many records should be returned, so not good to use `<=`.

File: tests/tests/database_api_tests.cpp [hunk 23]
```diff
@@ -692,4 +692,101 @@ BOOST_AUTO_TEST_CASE( lookup_vote_ids )
...
+   BOOST_CHECK(results.front().id > o.id);
+   // NOTE 3: because of NOTE 1, here should be little than 
+   BOOST_CHECK(results.front().sell_price < o.sell_price);
+   for (int i = 0 ; i < results.size() - 1 ; ++i) {
+     BOOST_CHECK(results[i].sell_price >= results[i+1].sell_price);
+   }
+
```
Comment (abitmore) [inline tests/tests/database_api_tests.cpp]: Test the scenarios that will return an empty vector or throw an exception?

**Comment by cifer-lee** [comment]
@abitmore have fixed reviews so far except the initialization of `upper_itr`, hard to initialize it at defining point because it depend on wether `ostart_price` is valid. And IMO it's ok to assign `upper_itr` in each `if/else` branch since more clearly to read.

btw, about code formatting, maybe we can uniform code style using an auto-formatting tool?

**Comment by abitmore** [comment]
> @abitmore have fixed reviews so far except the initialization of upper_itr, hard to initialize it at defining point because it depend on wether ostart_price is valid. And IMO it's ok to assign upper_itr in each if/else branch since more clearly to read.

`upper_itr` is only related to base and quote.

> btw, about code formatting, maybe we can uniform code style using an auto-formatting tool?

Of course you can use a tool. However, usually we only format new code and sometimes related old code for easier review (via diffing tool).

**Comment by abitmore** [comment]
@cifer-lee your commit history is not clear (duplicated commits and unrelated commits), please rebase.

File: libraries/app/database_api.cpp (hunk 18 above)
Comment (cifer-lee) [reply libraries/app/database_api.cpp]: has initialize upper_itr in each of if/else if/else branch, is it ok?

File: libraries/app/database_api.cpp [hunk 24]
```diff
@@ -680,12 +680,13 @@ vector<limit_order_object> database_api_impl::get_account_limit_orders( const st
    {
       // in case of the order been deleted during page querying
       const limit_order_object *p_loo = _db.find(*ostart_id);
+      upper_itr = index_by_account.upper_bound(std::make_tuple(account->id, price::min(base_id, quote_id)));
```
Comment (abitmore) [inline libraries/app/database_api.cpp]: This change slightly reduced performance under certain circumstances :)

Before this change, if an exception is thrown due to `FC_ASSERT` below, this database query won't be executed.

Comment (cifer-lee) [reply libraries/app/database_api.cpp]: performance reduction means if run into `FC_ASSERT`, `upper_itr` initialization is vain here?

Comment (abitmore) [reply libraries/app/database_api.cpp]: Correct.

**Comment by litepresence** [comment]
not sure if this helps, but this is how I sort my limit orders in one market / one account; sorted by orderNumber... on client side using websocket-client, in python, without pybitshares

https://pastebin.com/Bg2L78qB

returns of list of dicts with keys:
`price, amount, market, orderNumber, orderType`

**Comment by cifer-lee** [comment]
@litepresence Thanks~ but as have talked above, better to sorted first by price, then by order id

**Comment by cifer-lee** [comment]
@abitmore @jmjatlanta Thanks for your comments, I feel sorry for the partially covered test cases and the ambiguous api name. I have never written test cases before, so have no conscious about coverage, I will supplement the missing cases sooner.

The api name is derived from `get_limit_orders` api, I have no good idea how to make it clearer, maybe `get_limit_orders_by_account` looks clearer but the parameters indicates it was obviously not just "by account". Hearing from maturity too..
