### PR TITLE
Partially fix #511 assert() issue

### LINKED ISSUE #511: `assert()` in db_market.cpp and other source code?
Related discussion in https://github.com/steemit/steem/issues/1815:
>There are lots of `assert()` statements in `database::match()`. This ticket proposes changing them to FC_ASSERT(). (**The difference is that assert() is only triggered in debug builds.**) Some things to keep in mind about this kind of change:
> * (a) In general, recently the core devs' policy has been that it is acceptable to convert assert() to FC_ASSERT() statements for conditions that should never happen. The slight performance penalty is worth extra checking, defense in depth against potential bugs or exploits.
> * (b) Newly-added asserts must "fail safe" with regard to block production, FC_ASSERT() in per-block processing could shut down the blockchain, so we can't put any there.
> * (c) Newly-added asserts must "fail safe" with regard to consensus changes, any newly added FC_ASSERT() must be gated by a hardfork (which can be removed once the hardfork passes, assuming nothing that triggered the newly added FC_ASSERT() got into the chain).
>
> The implementation strategy for adding new FC_ASSERT() is fairly straightforward:
> * Change to FC_ASSERT(), replay, see if anything on-chain triggers assertions
> * If something triggers, we need to further analyze the issue
> * If nothing triggers, move FC_ASSERT() to if( has_hf_20 ) block
> * Once HF20 passes, remove if( has_hf_20 ) block, if we can replay then all is well (we can merge the > * removal of the if( has_hf_20 ) check and do FC_ASSERT() unconditionally)

### PR DESCRIPTION
**Pull request by abitmore**
This PR changes a few `assert()` to `FC_ASSERT()` which is described in #511 and also some other code related.

https://github.com/bitshares/bitshares-fc/pull/9 need to be merged and appended to this PR.

### CODE REVIEW

File: libraries/chain/include/graphene/chain/protocol/asset_ops.hpp [hunk 1]
```diff
@@ -229,7 +229,7 @@ namespace graphene { namespace chain {
 
       account_id_type fee_payer()const { return account; }
       void            validate()const {
-         FC_ASSERT( amount.amount > 0, "Must settle at least 1 unit" );
+         FC_ASSERT( !"virtual operation" );
       }
```
Comment (pmconrad) [inline libraries/chain/include/graphene/chain/protocol/asset_ops.hpp]: Hm, perhaps this requires a hardfork after all? What if the op turns up in a proposal?

Comment (abitmore) [reply libraries/chain/include/graphene/chain/protocol/asset_ops.hpp]: Yes, you're correct. I'll revert this change. Let's fix it more carefully in another PR.

**Comment by abitmore** [comment]
Reverted the code for #588. Please review again.
